server:
    port: 8080
spring:
    spring:
        application:
            name: bettingapp
    datasource:
        url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: Ov23liANJtlptzOkcnEb
                        client-secret: 37967d4b2345ae2be6fe7428b7ed69d7055c4f73
logging:
    level:
        org:
            springframework:
                security: TRACE #GitHub Login
management:
    endpoints:
        web:
            exposure:
                include: health, info
    info:
        env:
            enabled: true
info:
    app:
        name: bettingapp
        description: app to place bets
        version: 1.0
api:
    rapidapi:
        key: 11e4a7c2d8mshdb6fe70382b7851p1b726cjsnfcd5ff9d290c
        host: odds.p.rapidapi.com
        base-url: https://odds.p.rapidapi.com/v4